fix(isotp_sock.c): add CAN_ISOTP_WAIT_TX_DONE flag to ISOTP sockets
driftregion/iso14229 pull request #30
Opened 2024-05-13 14:52 UTC by muehlke

As of now, an UDS client run on the Linux ISOTP kernel module was not able to recognize a timeout error of a Flow Control frame not arriving in time after a multi-frame request. To fix this, the flag CAN_ISOTP_WAIT_TX_DONE is set on the socket. Otherwise writing the bytes of the SEND buffer to the ISOTP socket would incorrectly return the expected SEND buffer size, creating further problems like e.g. a timeout waiting on the response of the "sent"  request, since it was not really sent so the UDS server is not sending a response.

2024-05-19 18:31 UTC, driftregion requested changes
Thank you @muehlke .  Please address the feedback and consider adding yourself to [AUTHORS.txt](https://github.com/driftregion/iso14229/blob/main/AUTHORS.txt)

2024-05-19 18:31 UTC, driftregion commented on test/test_tp_compliance.c
> +    TPMockLogToStdout();
Please remove these lines. They are not necessary and make the test fail on tp_c
```suggestion
```

2024-05-19 18:31 UTC, driftregion commented on test/test_tp_compliance.c
> +
Same as above, please remove these lines. 
```suggestion
```

2024-05-19 18:31 UTC, driftregion commented on test/test_tp_compliance.c
> +        cmocka_unit_test_setup_teardown(TestISOTPFlowControlFrameTimeout, NULL, NULL),
Please use the default setup and teardown
```suggestion
        cmocka_unit_test_setup_teardown(TestISOTPFlowControlFrameTimeout, setup, teardown),
```

2024-05-19 18:31 UTC, driftregion commented on test/test_tp_compliance.c
> +    // -1 is expected as the elapsed 1s timeout raises an error on the ISOTP socket
make the comment match the assertion

```suggestion
    // failure is expected as the elapsed 1s timeout raises an error on the ISOTP socket
```

2024-06-14 13:27 UTC, closed without merging

2024-06-14 13:30 UTC, muehlke commented
Hi @driftregion, could you please delete this pull request from the repo. I'll make a new one. By mistake I committed with the wrong git username and email. I'll push everything as you mentioned but with the right git username and email.